version: "3.8"
services:
        master:
                image: mpi
                build: .
                volumes:
                        - ./project:/root/project
        worker:
                image: mpi
                build: .
                volumes:
                        - ./project:/root/project
 

